### ISSUE TITLE
Cab we please have .jackblackparty added?

### ISSUE THREAD

**Issue by marcharius** [avatarkava/BeavisBot#106]
I would love it if this command could be added.

Some gifs it could include:
https://media.giphy.com/media/v5l4VTC4tSmRO/giphy.gif
https://media.giphy.com/media/bDQcYdKix5gxq/giphy.gif
https://media.giphy.com/media/blEl99OgPQnNS/giphy.gif
https://media.giphy.com/media/8faYAzBjfQ3Go/giphy.gif
https://media.giphy.com/media/123nrTcg9bHnPi/giphy.gif

So many more!

Anyway thanks for looking and keep up the great work!

**Comment by avatarkava** [comment]
All set!

**Comment by marcharius** [comment]
SWEET!
