### ISSUE TITLE
New to nodejs

### ISSUE THREAD

**Issue by xSidewinderx** [avatarkava/BeavisBot#107]
I get this when I try to run it?
TypeError: Object #<PlugAPI> has no method 'tcpListen'

**Comment by avatarkava** [comment]
Have you run `npm update` to grab all of the packages (this works similar to composer, bower, etc)

**Comment by xSidewinderx** [comment]
Just tried it, with no luck. sorry heres the full line
TypeError: Object #<PlugAPI> has no method 'tcpListen'

**Comment by avatarkava** [comment]
Can you verify if you have a node_modules/ folder under your root project folder and what folders are in there if any?

**Comment by thedark1337** [comment]
@avatarkava I removed TCPListen in the latest version of plugAPI, that might be why.

**Comment by avatarkava** [comment]
Ah you may be running off a newer version than I.  I'll remove from my code :dart:

**Comment by avatarkava** [comment]
Try pulling again @xSidewinderx - Removed in 3a9499a5561562016e30f344bee2dda2ce95da2d

**Comment by xSidewinderx** [comment]
All good now, just need to learn how to setup Sequelize. :)
