### ISSUE TITLE
beavisbot won't run

### ISSUE THREAD

**Issue by ncboy20** [avatarkava/beavisbot#123]
i have problem running beavisbot all i keep getting is [PM2][ERROR] script not found : /home/ahrii/bot.js
script not found : /home/ahrii/bot.js
can someone please help me?

**Comment by avatarkava** [comment]
Have you had any luck getting this working?  May be able to help some now that the new year's rush has quieted down...

**Comment by ncboy20** [comment]
no luck on making it work :( 


 

/*<![CDATA[*/
 blockquote.c2 {border-left: 1px solid #cccccc; margin: 0pt 0pt 0pt 0.8ex; padding-left: 1ex}
 p.c1 {color: #666; font-size: small}
/*]]>*/


 
----- Reply to message -----
Subject: Re: [avatarkava/beavisbot] beavisbot won't run (#123)
Date: 2017. gada 21. janvāris 19:01:00

**Comment by avatarkava** [comment]
Well, let's diagnose if it's an issue w/ PM2, your configuration, or the code itself.  Can you run `node bot.js` from the directory where you have this installed?  Once you get it running from there and connecting properly, then maybe working through PM2 config is possible (I'm no expert).
