### ISSUE TITLE
Discord webhooks?

### ISSUE THREAD

**Issue by Permanently** [avatarkava/beavisbot#141]
Since Discord now have webhooks, would it be possible to add it to the bot? :)

**Comment by avatarkava** [comment]
It's definitely possible - what did you have in mind for functionality?

**Comment by Permanently** [comment]
Just the same features as Slack, I guess :P

**Comment by avatarkava** [comment]
Discord doesn't support outbound webhooks (for posting back to the bot to do things like grab logging or restart it), but I've implemented posting to both Discord and Slack on events.

Please check the updated config.json as the structure has changed some.  You'll also need to remove configState.json to make sure it picks up the structure changes.

**Comment by Permanently** [comment]
Not gonna lie, I completely forgot about this.

**Comment by avatarkava** [comment]
To be fair it only took a year :)
