### ISSUE TITLE
Extensions path doesn't exist

### ISSUE THREAD

**Issue by Permanently** [avatarkava/beavisbot#142]
I'm getting this whenever I run the bot:

> Loaded config file from /root/beavisbot/config.json
> 01:25:21s 140ms [Info]      [PlugAPI]       Running plugAPI v5.0.0-beta.2
> [YOUTUBE] Authenticating with youtube...
> [YOUTUBE] Authenticated! "youtubeApiKey"
> [INIT] Events loaded...
> [INIT] Commands loaded...
> Unable to load extension:  Error: ENOENT: no such file or directory, scandir '/root/beavisbot/extensions/'
>     at Error (native)
>     at Object.fs.readdirSync (fs.js:951:18)
>     at loadExtensions (/root/beavisbot/functions/init.js:48:16)
>     at initializeModules (/root/beavisbot/bot.js:50:5)
>     at /root/beavisbot/bot.js:28:9
>     at /root/beavisbot/node_modules/plugapi/lib/client.js:1171:32
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> /root/beavisbot/node_modules/handle-errors/index.js:90
>     throw new TypeError('[handle-errors] expect `' + name + '` be string')
>     ^
> 
> TypeError: [handle-errors] expect `msg` be string
>     at checkType (/root/beavisbot/node_modules/handle-errors/index.js:90:11)
>     at Object.newError [as error] (/root/beavisbot/node_modules/handle-errors/index.js:53:5)
>     at Immediate.<anonymous> (/root/beavisbot/node_modules/plugapi/lib/client.js:1187:42)
>     at runCallback (timers.js:649:20)
>     at tryOnImmediate (timers.js:622:5)
>     at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by avatarkava** [comment]
Directory should be created automatically with 0700214e2c037f1a53cbfe411f57f5252f16e667
