### ISSUE TITLE
Lottery counts recently joined users without chatting

### ISSUE THREAD

**Issue by OperationXIV** [AvatarKava/BeavisBot#66]
If a person joins the room when Beavis is about to announce the lottery winner, he will pick the person who recently joined before they get the chance to type in chat. Disconnects don't seem to count, only the ones that Beavis greets with a welcome message. 

![lotterybug](https://cloud.githubusercontent.com/assets/7161948/4969154/b2bb37c6-6859-11e4-9a4b-f5a29dbad494.PNG)

(More screenshots via Slack, 10/29 and 11/9)

**Comment by Piratelizz** [comment]
This just happened again with the roulette. User Rhaj entered the room, joined the line, then won the roulette without chatting.

**Comment by AvatarKava** [comment]
This will be "fixed" once we turn on requiring someone to chat a specific command to join the contest list.  Not too much point fixing it before then.
