### ISSUE TITLE
BeavisBot removes an entire group of messages

### ISSUE THREAD

**Issue by tamias** [AvatarKava/BeavisBot#67]
Enter a normal message, then a dot message (e.g. ".", ".rules").  Now that plug.dj groups consecutive messages from a single user, BeavisBot removes the entire group of messages, instead of just the dot message.

**Comment by AvatarKava** [comment]
Unfortunately this can't be truly fixed since plug groups them all with an identical ID.  The alternatives are turning off the removal entirely or leaving it in as-is.  I'm going to do the former and have Beavis stop removing '.'.
