### ISSUE TITLE
Request - Add @djs mention to the lotto & roulette message

### ISSUE THREAD

**Issue by bratpantz** [AvatarKava/BeavisBot#71]
It would be nice if when Beavy Poo announces a lottery/roulette that it includes the @djs mention

Maybe at the beginning like:     @djs Wait list lottery in 5 minutes! Join the line and chat within 5 minutes to enter. Winner gets the #1 spot!

**Comment by AvatarKava** [comment]
Good idea!  Added!  ~ Rose :D

**Comment by bratpantz** [comment]
hahaha thank you Rose!
