### ISSUE TITLE
add new command and pictures from bot upon receipt

### ISSUE THREAD

**Issue by perfectofc** [AvatarKava/BeavisBot#92]
.shun - useful for theme days : http://cf067b.medialib.glogster.com/media/17/17f24350f6b62a842781e184ada36673ea04677cbcf0ae6a0ab1eacdd2fb3d86/shun-the-non-believer-jpg.jpg

**Comment by AvatarKava** [comment]
Added!

**Comment by perfectofc** [comment]
Awesome!  <3
