### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by choccat** [avatarkava/BeavisBot#93]
Hello,
I cannot find any other way to contact you so I'm contacting you here. Please could you assist me with setting up the bot on a vps? What is the bes VPS to buy?
Thanks.

**Comment by AvatarKava** [comment]
Hey, did you manage to get something working? :)

**Comment by choccat** [comment]
Sadly not, I'm not very good with VPS yet. :(

**Comment by omfgitsasalmon** [comment]
It's not hard to learn tbh. @choccat

**Comment by avatarkava** [comment]
Hey @choccat - if you're still having issues, please email me at the address in my profile and I may be able to help some w/ setup or at least point you in the right direction.
