### ISSUE TITLE
Change Command Literal

### ISSUE THREAD

**Issue by choccat** [avatarkava/BeavisBot#95]
Is there anyway to change . to !
Thanks, <3

**Comment by AvatarKava** [comment]
Currently no way other than changing the references in bot.js and everything in the /commands folder, which you should be able to do on your own checkout without much incident.

I can definitely look at this as a future development item, though.

**Comment by choccat** [comment]
For example, if I found every .add in bot.js and changed it to !add and did the same in the add.js, that would work?
